### ISSUE TITLE
FFFFFFFF ID

### ISSUE THREAD

**Issue by aknik** [Crypter/RFID-Skimmer#1]
void prepare_data(uint32_t ID, uint32_t VENDOR){
  value[0] = (VENDOR>>4) & 0XF;
  value[1] = VENDOR & 0XF;
  for (int i=0; i<8; i++){      <<<<<<<< i must be 0 for FFFFFFFF ID
    value[i+2] = (ID>>(28-i*4)) &0xF;
  }

**Comment by Crypter** [comment]
That ID is impossible to get since the ID contains numbers from 0-9 in real world, no letters. I will check tho, since you might be right.
